### ISSUE TITLE
I use Github for code, not social justice politics

### ISSUE THREAD

**Issue by bashu** [todogroup/opencodeofconduct#102]
Can we let people do what they do best, instead of competing in victim olympics?

**Comment by Croydon** [comment]
Projects can decide their own policies. It's up to every single project if they adopt this or any kind of Code of Conduct. It's up to every single person if they want to contribute to a project which has a Code of Conduct or which hasn't. 

As I read first such comments as yours I didn't understand where this, as it seems non constructive, critics are coming from and I found some people who are basically trolling projects for not having a Code of Conduct. So I can get now the basic idea, where comments like yours are coming from.

However, you should realize that these trolls got you to a point, where you aren't constructive by yourself anymore as well.
Again: Every project can decide if they want to have this or another Code of Conduct or not. Every single person can decide if they want to contribute in every single project or not.

So...
Stop trying to force projects TO USE a Code of Conduct.
Stop trying to force projects NOT TO USE a Code of Conduct.

**Comment by CoWinkKeyDinkInc** [comment]
You haven't realized that this project is basically done for?  GitHub basically ditched it in August, but you and other people just won't let this non-issue die down.
