### ISSUE TITLE
How should spaces be encoded in the fragment?

### ISSUE THREAD

**Issue by bkeepers** [todogroup/opencodeofconduct#15]
If you configure a project with a space in the name, it uses a space in the URL: `http://todogroup.org/opencodeofconduct/#Git LFS/opensource@github.com`. Is this even a valid URI?

If `encodeURIComponent` is called on each of the parts, then it would result in: `http://localhost:4000/#Git%20LFS/opensource%40github.com`, which is a bit uglier, but does not break.

/cc @rubyist @josh

**Comment by josh** [comment]
Is `/opencodeofconduct/#Git LFS/opensource@github.com` is supposed to be the full path? Or is `#Git LFS/opensource@github.com` the fragment?

For path components, space really should be encoded as `%20`. You can do the `+` hack if its in the query string.

**Comment by bkeepers** [comment]
> Is `/opencodeofconduct/#Git LFS/opensource@github.com` is supposed to be the full path? Or is `#Git LFS/opensource@github.com` the fragment?

It's the fragment. This just a pages site, so it's using JavaScript to grab the fragment. We could switch to using a query string.
