### ISSUE TITLE
Choose better word than "uphold" in apply clause

### ISSUE THREAD

**Issue by mojavelinux** [todogroup/opencodeofconduct#16]
Currently, the recommended clause for applying the code to a project is as follows:

> This project adheres to the [Open Code of Conduct][code-of-conduct]. By participating, you are expected to uphold this code.

I think we can choose a better word than "uphold". First, it may not translate well for a non-native speaker (even being a native speaker it feels a bit awkward). Second, it reads more like you back it up in light of a challenge rather than something you plan to put into practice yourself. It's only slightly stronger than "observe". We want the focus to be on the application of the code.

The most fitting replacement that comes to my mind is "abide by", though I recognize that may come across as rather demanding. Other options include "follow", "respect", "honor", "practice", "comply with" or "adhere to". I think "practice" may be the most gentle. In casual speech, I've always heard my elders use the word "honor" or "follow" in this context ("you are expected to follow this code"). The code of conduct itself uses the term "honor" (honored) for this purpose several times.

**Comment by caniszczyk** [comment]
Thanks @mojavelinux, I agree with your sentiments.

**Comment by mojavelinux** [comment]
:+1:

**Comment by romeosavala** [comment]
Thank you, as I will "uphold" the code of conduct with freat pleasure, thank you the notice @mojavelinux :-)

**Comment by romeosavala** [comment]
Great typo...
