### ISSUE TITLE
Consider Merging with Already Adopted Code of Conduct

### ISSUE THREAD

**Issue by sigmavirus24** [todogroup/opencodeofconduct#2]
See https://github.com/CoralineAda/contributor_covenant and the list of groups that have already adopted it. /cc @CoralineAda

**Comment by caniszczyk** [comment]
I tried to answer this question here: https://github.com/todogroup/opencodeofconduct#can-i-use-something-simpler-what-about-the-contributor-covenant

We definitely call out other CoCs here and thank them appropriately: https://github.com/todogroup/opencodeofconduct#thanks
