### ISSUE TITLE
Revert removal of attribution from README.md

### ISSUE THREAD

**Issue by willingc** [todogroup/opencodeofconduct#20]
Please revert PR  #19 removal of the detailed list of organizations in the Thanks section of the README.md file.

The organizations deserve attribution for their long-standing work in both the CoC and the README. The README is one of the first documents a developer will see when visiting the repo. Appropriate recognition and thanks should be prominent in the README for all community members to view easily (without having to click through to a website).

**Comment by caniszczyk** [comment]
Fixed, thanks!
