### ISSUE TITLE
Maybe mention SWATing?

### ISSUE THREAD

**Issue by vgturtle127** [todogroup/opencodeofconduct#22]
I think that due to the fact that this seems to be a common occurrence (maybe even more so then doxing), it might be a good idea to say that doxing and/or SWATing should be against the rules too, but it doesn't necessarily just mean people streaming video. It could also be SWATing from VOIP, IRC, maybe you know where the person lives by some other means, etc.

Any thoughts would be nice. :smile: 

I would do a pull request, but I didn't know how well this would be received.

**Comment by caniszczyk** [comment]
@vgturtle127 we are looking at updating the explicit harassment definitions here:
https://github.com/todogroup/opencodeofconduct/pull/17

We may link to the definitions listed in the [GF](http://geekfeminism.org/about/code-of-conduct/) as an example of unwarranted behavior. Not sure if that will cover it, but let us know.

**Comment by caniszczyk** [comment]
@vgturtle127 I need more coffee this morning, my previous post was a mistkae.

I believe this is mentioned in the **Be careful in the words that you choose" section**:

> Posting (or threatening to post) other people’s personally identifying information (“doxing”).

Let me know if that works!

**Comment by vgturtle127** [comment]
Well, my thought was that doxing is only the first part of the SWATing. After that, they have to call the police and pretend somebody is in danger or something (a crime all by itself). So, maybe after that sentence you could add something about using identifying information against somebody? I don't know, tell me what you think.

**Comment by Addvilz** [comment]
SWATing as you call it is illegal and is covered by law. We should not include obviously illegal conduct as prohibited, as it would be superfluos and for the same reason we should not include murder or theft.

**Comment by vgturtle127** [comment]
I guess that's true, but there isn't any law against any part other than calling the police without just cause, so maybe just include the part about misuse of identifiable information?

**Comment by CoWinkKeyDinkInc** [comment]
Stalking users is already under this list, which you need private info to call the SWAT on somebody.

**Comment by NuckChorris** [comment]
@CoWinkKeyDinkInc not always the case. My address and phone number are both attainable without stalking (honestly, I just hand them out), but that doesn't mean I shouldn't be protected from SWATing

**Comment by bkeepers** [comment]
Thanks for your feedback. See https://github.com/todogroup/opencodeofconduct/issues/84.
