### ISSUE TITLE
"we all agree that everyone is equal" is vague and possibly incorrect

### ISSUE THREAD

**Issue by ericschultz** [todogroup/opencodeofconduct#25]
I appreciate what todogroup is doing. I do have some concerns about the wording of the diversity statement, particularly the statement: "Although we may not be able to satisfy everyone, we all agree that everyone is equal."

This can be interpreted in two ways. First it could mean that the project feels everyone coming into the project is equal in some manner. What that manner happens to be is unclear. In many manners, I don't think there's much disagreement that people are not treating equally in our society so this is a demonstrably false statement.

The second manner of interpretation is that people are treated equally in the project. I don't think it's clear that you mean this from the language. This is slightly better but will likely not be managed since very few communities, if any, have succeeded at treating folks entirely equally. Additionally, you explicitly contradict that everyone is equal within the project by implying later mentioning the value of honoring diversity and particular groups. In that case, you seem to imply that fairness is more important that equality in some situations. I think that's correct but it contradicts the previous statement on equality.

One potential way to fix this strange contradiction is to rewrite the sentence "Although we may not be able to satisfy everyone, we all agree that everyone is equal." as "Although we will fail at times, we all agree that everyone is valued. We seek to treat everyone both as fairly and equally as possible."

I don't know if this is a satisfactory change but I think a change should be made.

**Comment by caniszczyk** [comment]
Thanks for your suggestion, I can see what you mean by a contradiction.

We are in the process of collecting feedback from initially launching this and will incorporate changes in the coming weeks based on community feedback.

**Comment by bkeepers** [comment]
Merged #28, which updated this.
