### ISSUE TITLE
Adding language that clarifies complaints that will not be acted upon

### ISSUE THREAD

**Issue by jdax** [todogroup/opencodeofconduct#26]
In the Code of Conduct created by Geek Feminism, which is currently considered a community standard, it addresses which issues will not be addressed. This list adds a sense of safety to marginalized people, like myself, knowing we won't be written up for asking not to be harassed. The below list is list of "tools" our oppressors often use against us, and under the current Open COC, we could get in trouble for not liking it.

The Geek Feminism community prioritizes marginalized people’s safety over privileged people’s comfort. The Geek Feminism Anti-Abuse Team will not act on complaints regarding:

‘Reverse’ -isms, including ‘reverse racism,’ ‘reverse sexism,’ and ‘cisphobia’ (because these things don’t exist)
Reasonable communication of boundaries, such as “leave me alone,” “go away,” or “I’m not discussing this with you.”
Refusal to explain or debate social justice concepts
Communicating in a ‘tone’ you don’t find congenial
Criticizing racist, sexist, cissexist, or otherwise oppressive behavior or assumptions

**Comment by caniszczyk** [comment]
Thanks for your feedback, we are working on part of this in this PR:
https://github.com/todogroup/opencodeofconduct/pull/24

We are in the process of collecting feedback from initially launching this and will incorporate changes in the coming weeks based on community feedback.

**Comment by jdax** [comment]
I am looking at the commit and I do not see how the commit in that PR addresses this issue. It links to GF, and clarifies that the definition of harassment comes from GF, but does not address the point about complaints made with the intent to silence marganilized people.

**Comment by caniszczyk** [comment]
If you have suggestions on text to add, change or modify, please submit something as a discussion point. PRs are generally the best way to help with this.

**Comment by jdax** [comment]
No. The work of writing concise, enforceable Codes of Conduct that truly uphold the safety of marginalized people over the comfort of bigots has already been done. You can find this at GeekFeminism, Contributor Covenant,and Citizens Code of Conduct. We, as a community, have already created and set these standards. We have been working hard to try to find a way to collaborate with GitHub, major and minor conferences, meet ups, and slack channels to create a safe community in which EVERYONE feels comfortable and safe contributing. We are not doing this work AGAIN for the benefit of the corporate members of TODO Group. Doing so would REMOVE us from our YEARS of work, it would be doing UNPAID labor for group of start ups and companies, and not even getting the cheap compensation of "exposure." 

You want to write a GOOD code of conduct? You do it yourself. I posted a suggestion. That is the amount of free labor you get out of me. Your other option: Work WITH Geek Feminism, Coraline Ehmke, and other community members to implement an easy CoC feature on Github. Instead of reinventing this CoC wheel, add a drop down box to Github that would let people choose (much like they choose from multiple licenses) if they would like GeekFeminism, Contributor Covenant, or Citizen's Code of Conduct.

**Comment by Addvilz** [comment]
This issue provides little value and is with a clear goal of emphasizing goals of one particular community, which is in a direct conflict to the ultimate goal of this project - to build a culture of respect without discrimination and with culture of equality across communities. Suggestion made in this issue promotes none of that, as it directly emphasizes rights of one group above another and demotes discussion and reasoning by preventing contest of the issues by explicitly banning different opinions.

In addition to that, the last comment of the author is rude, not constructive and provides no value to the issue. If you have something to contribute, do so. If not, this issue has no future.

As a side note, "community standard", as you said, is yet to become one. At this point I don't see that it has much influence outside the group of origin, nor is it widely accepted.

**Comment by Haacked** [comment]
> In addition to that, the last comment of the author is rude, not constructive and provides no value to the issue. If you have something to contribute, do so. If not, this issue has no future.

Likewise, your comments are dismissive as well. I don't think the [tone policing](http://geekfeminism.wikia.com/wiki/Tone_argument) is necessary. It's derailing and doesn't address the actual points made.

> Instead of reinventing this CoC wheel, add a drop down box to Github that would let people choose (much like they choose from multiple licenses) if they would like GeekFeminism, Contributor Covenant, or Citizen's Code of Conduct.

@jdax I personally really like this idea. It's very much in the spirit of the license picker (which I was involved with). I raised your suggestion with others at GitHub who are in a better position to give it due consideration. I can't make promises since I don't work on the teams that own this area of the site, but your suggestion has been heard. Thanks!

**Comment by Addvilz** [comment]
> Likewise, your comments are dismissive as well. I don't think the tone policing is necessary. It's derailing and doesn't address the actual points made.

Taking a sentence out of context and declaring it tone argument, completely ignoring everything else stated in the comment is [cherry picking](https://en.wikipedia.org/wiki/Cherry_picking_(fallacy)) and [abuse](http://feministing.com/2015/04/23/words-for-cutting-why-we-need-to-stop-abusing-the-tone-argument/) of the tone argument. My comment contains 4 paragraphs - please, consider all of them. Any comments regarding that are welcome.

**Comment by ciafwywcoc** [comment]
jdax, this is all irrelevant to open source development.

**Comment by bkeepers** [comment]
This was added in #17
