### ISSUE TITLE
Include confidentiality clause

### ISSUE THREAD

**Issue by VolatileDream** [todogroup/opencodeofconduct#27]
Complaints under a Code of Conduct should confidential by default. A confidentiality clause is important to clarify who ( and under what circumstances ) has access to the information in a complaint. The text below suggests that complaints are not confidential by default, and that the complaint could be shared beyond the response team unless the complainant requests otherwise.

> We will respect confidentiality requests for the purpose of protecting victims of abuse.

From: https://github.com/todogroup/opencodeofconduct/blame/gh-pages/index.md#L43

It's my hope that there is a generic way to specify these things, but there may not be.

**Comment by caniszczyk** [comment]
Thanks for your feedback, we will definitely consider doing this.

We are in the process of collecting feedback from initially launching this and will incorporate changes in the coming weeks.

**Comment by VolatileDream** [comment]
It's awesome to see this project exist. I applaud the effort going into it. /aside

I also have an [example of a confidentiality clause](https://csclub.uwaterloo.ca/about/code-of-conduct.html#confidential), which I hope helps.

**Comment by bkeepers** [comment]
Thanks for your feedback. See https://github.com/todogroup/opencodeofconduct/issues/84.
