### ISSUE TITLE
Diversity through free speech

### ISSUE THREAD

**Issue by Michaelfemdom** [todogroup/opencodeofconduct#30]
The way the  ´free speech´ is basically defined ( https://xkcd.com/1357/ ) , leaves it open for abuse, as we have seen happen in different communities.

We have seen people being fired from their jobs, shows being cancelled etc. This is mob rule mentality which is now being rationalized in a way  that it seems just as valid as any other view of free speech or activism.

We are living in times where society is under pressure to change and be more equal, accepting, understanding. This shift in attitude gives minority groups considerable amount of social power which can be abused if it is focused on individual or small group of individuals, even if they would be part of so called "privileged group".

Guidelines, code of conducts should be worded in a way that they cannot be abused instead of rationalizing kneejerk reaction and mob rule mentality, as it has been done in ´social justice movement´ , where outing people, contacting employers and getting people fired for jokes about dongles,  has become acceptable way of  _conducting_ conversation. 

These kind of attitudes are divise and assume bad faith first IMHO.
Also they can have exactly the opposite effect on community, instead of creating diversity they can create oppressive environment.

In order for society and people to grow, they need room to grow. 
That room is created by  not just free speech as a right, but right to be heard.

**Comment by ciafwywcoc** [comment]
Exactly, free speech and inclusivenes also includes the right express a currently to an unpopular opinion. The CIAFWYWCOC I wrote emphasises this as well.

**Comment by bkeepers** [comment]
@Michaelfemdom thank you for sharing your concern. It is up to each community that adopts the code of conduct to make it their own and uphold it.

If you have any suggested edits to the template, please open a pull request and the community can discuss them.
