### ISSUE TITLE
Expand on the impartiality of the response team

### ISSUE THREAD

**Issue by tkerber** [todogroup/opencodeofconduct#31]
The code of conduct explicitly states that the person handling complaints should not be the person being accused:

```If the person who is harassing you is part of the response team, they will recuse themselves from handling your incident.```

I see this as the intention to guarantee the impariality of the response. It does not, however take into account a case where the complaint originates from a member of the response team.

It is not in the interest of impartiality for this member to handle their own complaint. It suggest expanding the statement to include all involved parties.

**Comment by Addvilz** [comment]
I have opened a pull request to address this issue. Could you please review it and let me know what you think? :)

**Comment by bkeepers** [comment]
#32 was merged to address this. Let us know if there are any concerns with that.
