### ISSUE TITLE
Improve on transparency and define governance

### ISSUE THREAD

**Issue by Addvilz** [todogroup/opencodeofconduct#36]
It needs some clarification on how is this project governed, by whom, what is the approval process for contributions and by whom. 

We can of course look at the list of contributors, take a peek at the @TODOGroup page, but that does not really explains much beyond that this is a project of group of X people from X companies.

Example governance information from IO.JS https://github.com/nodejs/io.js/blob/master/GOVERNANCE.md

**Comment by caniszczyk** [comment]
I agree, essentially @todogroup/owners have the commit bit and make the final decision.

We will add a CONTRIBUTING.md to make this more clear. No need for a crazy governance document yet outside of stating what expectations are for contributing and committing in the CONTRIBUTING.md and then linking it off the README.md

**Comment by Addvilz** [comment]
Nobody outside the @todogroup/owners can actually see who is in that team. :)

**Comment by caniszczyk** [comment]
We will make things clearer in the CONTRIBUTING.md

**Comment by bkeepers** [comment]
See https://github.com/todogroup/opencodeofconduct/issues/84.
