### ISSUE TITLE
todogroup.org and this community do not have a code of conduct

### ISSUE THREAD

**Issue by epsalon** [todogroup/opencodeofconduct#37]
Specifically, where do I report harassment and unacceptable behavior occurring in this community?

**Comment by Addvilz** [comment]
I think it's reasonable to assume that we should fallow the same code of conduct we are contributing to. As to the reporting harassment - I did not find any reference to that either.

Maybe @bkeepers could clarify?

**Comment by epsalon** [comment]
The code of conduct document here is a template. The abuse@todogroup.org address that was suggested in the template bounces.

**Comment by Addvilz** [comment]
Yes, it is indeed a template, but I guess we should probably stand by the guidelines we ourselves created and are contributing to.

Maybe we can explicitly state in the readme that we ourselves do adhere to the CoC along with the abuse contact?
