### ISSUE TITLE
Proposal for handling versioning

### ISSUE THREAD

**Issue by bkeepers** [todogroup/opencodeofconduct#38]
The [current version](https://github.com/todogroup/opencodeofconduct/blob/gh-pages/index.md) is labeled "1.0", but no releases have been tagged in git.

I propose we use [semantic versioning](http://semver.org/). Given a version number `MAJOR.MINOR.PATCH`, increment the:

- `MAJOR` version when changing the intent, drastically changing the format, or adding significant sections
- `MINOR` version when adding small amounts of content that is consistent with the spirit of the code
- `PATCH` version when fixing, clarifying, or expanding on wording of existing content.

## Releases

This is a GitHub pages site, so the `gh-pages` branch (which is currently the default branch) is what dictates what shows up on the web. I propose we add a `master` branch, and a release script which tags the latest version and pushes it to the `gh-pages` branch.

Additionally, I think we should make a copy of each major version reference-able by url. e.g. `http://todogroup.org/opencodeofoconduct/v1/`.

## Questions

- Since no versions have been tagged in git, could we consider the content so thus far to be "pre-release" and tag 1.0 as soon as some of the currently open pull requests are merged (e.g. #17)?

Thoughts?

**Comment by caniszczyk** [comment]
This sounds perfect IMHO

**Comment by Addvilz** [comment]
Yes, this makes all the sense in the world - especially the URL. 

As to your question, I think that is a good idea. :)

**Comment by bkeepers** [comment]
See https://github.com/todogroup/opencodeofconduct/issues/84.
