### ISSUE TITLE
reverse bullying

### ISSUE THREAD

**Issue by SuperDoxin** [todogroup/opencodeofconduct#59]
the current wording and content of the OCoC allow for "reverse bullying". you can enter an project using the OCoC and yell harassment loud and often enough and you can easily bog down the entire project in harassment claims.

maybe a "good faith" clause would be a good idea?

**Comment by jaredallard** [comment]
:+1:

**Comment by mvirkkunen** [comment]
[Note: I explicitly do not consent to the code of conduct as it is due to multiple issues]

>implying SJWs will not bend any "good faith" clause out of shape in a microsecond

**Comment by SuperDoxin** [comment]
> Implying SJWs will not bend any "good faith" clause out of shape in a microsecond

that doesn't mean we should give them ammunition.

**Comment by bkeepers** [comment]
Thanks for your feedback. See https://github.com/todogroup/opencodeofconduct/issues/84.
