### ISSUE TITLE
CNAME to a real domain?

### ISSUE THREAD

**Issue by bkeepers** [todogroup/opencodeofconduct#6]
Where do we want this to live? Right now it's accessible at https://todogroup.org/opencodeofconduct. Do we want these type of resources under the TODO umbrella? What do you think about having it live at its own domain?

A few domain ideas:

- opencodeofconduct.com
- codeofconduct.io
- codeofconduct.github.io (https://github.com/CodeOfConduct is dormant)

I could go either way. If we want it on todogroup.org, it might be nice to make some tweaks to the website to create a landing place for these resources.

**Comment by caniszczyk** [comment]
@bkeepers I own opencodeofconduct.org, however, I think it should live within the todogroup.org domain or at least have it prominently featured that this came from the TODOGroup

**Comment by bkeepers** [comment]
> …or at least have it prominently featured that this came from the TODOGroup

Definitely.

**Comment by bkeepers** [comment]
I'm :+1: for leaving this on todogroup.org

**Comment by bkeepers** [comment]
I'm actually having second thoughts about this now. opencodeofconduct.org is a lot easier to remember than todogroup.org/opencodeofconduct.  We could still keep a strong connection to todogroup.org (#11).

What do you think?

**Comment by caniszczyk** [comment]
I can always setup a redirect via opencodeofconduct.org to todogroup.org/opencodeofconduct

**Comment by bkeepers** [comment]
@caniszczyk I'm still leaning towards having this on its own domain. I feel like the current design makes it clear enough that this is from TODO Group. Is there any other advantage to having this on the todogroup.org domain?
