### ISSUE TITLE
Scope not clear

### ISSUE THREAD

**Issue by tzs** [todogroup/opencodeofconduct#62]
There should be some kind of explicit statement of scope. I am not sure from the text how wide it applies.

For example, suppose Alice (a white female) and Bob (a black male) are members of the community of project X, which uses this CoC.

Further suppose that Alice and Bob are also both members of some other community, such as a forum for an online game they both play. That community has no connection to project X, other than some members of it are also members of the X community.

In that forum, discussion is often heated and nasty. Suppose Alice makes racist remarks about Bob in that forum, or Bob makes sexist remarks about Alice in that forum.

Would those remarks in that outside forum be violations of the Project X CoC, since Alice and Bob are both X members? Or are they out of scope because they did not take place in X forums, mailing lists, IRC, etc.?

**Comment by asiekierka** [comment]
That is a difficult question, as the line between personal life and project public relations is very blurry and it is hard to find a border which satisfies everyone.

**Comment by bkeepers** [comment]
Thanks for your feedback. See https://github.com/todogroup/opencodeofconduct/issues/84.
