### ISSUE TITLE
Lack of underrepresented minorities on the contributors team.

### ISSUE THREAD

**Issue by just3ws** [todogroup/opencodeofconduct#66]
https://github.com/todogroup/opencodeofconduct/graphs/contributors

Of the 11 contributors there seems to be a severe lack of diversity on the team. Only two females and everyone appears to be white males. There does not appear to be any persons of color and only cisgendered (as best I can tell from an avatar). Also are any non-heterosexuals represented on the team.

![](https://www.evernote.com/l/AA35lCsD3lBB7ICutxD4ASrmKgCQXvWwOmwB/image.png)

Why is that the case? If the purpose is to amplify underrepresented voices then why has the core team not included underrepresented minorities as part of their core team?

**Comment by caniszczyk** [comment]
The Open Code of Conduct purpose is fairly well defined in the FAQ:
https://github.com/todogroup/opencodeofconduct#why-a-code-of-conduct

Contributions are welcome from everyone as stated in the FAQ: https://github.com/todogroup/opencodeofconduct#can-i-contribute-and-improve-this-code-of-conduct

**Comment by just3ws** [comment]
How are you actively seeking to amplify underrepresented voices?

**Comment by lleaff** [comment]
@just3ws There is nothing in the Open Code of Conduct FAQ or content that hints at positive discrimination. I think the goal is simply to avoid discrimination, negative or positive.

**Comment by just3ws** [comment]
@lleaff 

> Our open source community prioritizes marginalized people's safety over privileged people's comfort.

![](https://www.evernote.com/l/AA1FNvMDEg1LnICxNpgRRqjx2lX8B0jIcl8B/image.png)

I have read many calls for white, male, heteronormative people to stop speaking on behalf of people of color, women and other minorities. Yet, here we have a group of seemingly all white, mostly male people whose response to asking how they are helping to amplify minority voices and the response is basically, "Read the FAQ" and that says they accept Pull Requests. That is putting the onus on the minorities to submit their requests for consideration by a panel of white (mostly) men. Either they are building a safe place where minorities are represented or they are looking to show how altruistic and progressive they are for their own purpose.
