### ISSUE TITLE
Confusion about what constitutes "reverse"

### ISSUE THREAD

**Issue by atarzwell** [todogroup/opencodeofconduct#67]
Good work on implementing a CoC, while I've been lucky enough never seen any of theses issues in this community, making what is acceptable and unacceptable explicitly clear to the community is very important. Thanks! :+1: 

However, I'm not clear on the whole "reverse" things and googling "reversisms", "reverse-racism", etc seems to indicate it's a contentious issue. 

I'm not sure how to tell the difference between sexism and "reverse-" sexism. However the mention of "cisphobia" is clear in indicating which "side" is protected.

However reverse-racism and reverse-sexism are not defined. Since this is a worldwide group it would seem that this could vary based on locale which would only make it more confusing.

As a programmer unversed and uninterested in social activism it would be a lot better to make this explicit so I can respect and abide by it without having to study and research the issues it's trying to correct.

Can we get a definition of what groups are protected and which ones are not?

(Eggshells: As mentioned above, I do not mean to offend or instigate, if I have phrased something poorly please accept my apology as that is not my intention, explain the problem to me and I will attempt to reword)

**Comment by ConcernedUsurper** [comment]
This is already being discussed elsewhere!

MrStonedOne/opencodeofconduct#1

todogroup/opencodeofconduct#68

**Comment by mvirkkunen** [comment]
Maybe it's purposefully ambiguous, so if some time in the future the tables flip and say, women are generally considered the "privileged" group and men become "marginalized", misogyny is then OK.

**Comment by cperciva** [comment]
+1

This problem occurred to me while reading some discussions elsewhere: Some people seem to be interpreting "reverse racism" to mean "affirmative action programs", while other people are interpreting "reverse racism" to mean "any discrimination against members of historically privileged races".  I think clarifying the intended meaning would make it much easier to have constructive discussions about those clauses.

**Comment by bkeepers** [comment]
@atarzwell thanks for constructively engaging the conversation. We are working on clarifying the reverse-isms.

In the mean time, here are some links I've found helpful:

- [Why there's no such thing as "Reverse Racism"](http://www.dailykos.com/story/2010/07/15/884649/-Why-there-s-no-such-thing-as-Reverse-Racism)
- or in video form: [Comedian Aamer Rahman on Why 'Reverse Racism' Doesn't Work](http://www.huffingtonpost.com/2013/12/03/aamer-rahman-reverse-racism-_n_4379326.html)

**Comment by mvirkkunen** [comment]
@cperciva Aren't those two the same thing though?

E.g. if you purposefully favor hiring people from certain minority groups, you are at the same time discriminating against members of the majority. Two sides of the same coin.

**Comment by NuckChorris** [comment]
doesn't this

>whole population operating in a social structure that actually makes it difficult for a person not to discriminate

Literally describe the structure we've created by completely excluding certain people from protections? As a gay dude, I would never wish for the right to hate on straight guys, and see no reason to protect that.

**Comment by cperciva** [comment]
@mvirkkunen Affirmative action is *a* form of discrimination, yes.  But my point is that it isn't *the only* form of discrimination; and many people consider affirmative action to be justifiable in a way that many other forms of discrimination aren't.  What I'm asking to have clarified is how broad the term is intended to be.

**Comment by atarzwell** [comment]
@bkeepers 

First link: [WALL OF TEXT] 
Second link: An entertaining 2:50 clip of a comedian that succinctly summarizes the issue. 
This is a good combo. If it wasn't for the fact that I've never met you I'd say you know me well. :smiley: 

That said, while I usually learn just enough to not be a jerk I read through the first link entirely. They make a pretty good point, while I agree with much of it, it's not really relevant to a software development community. 

> Prejudice is an irrational feeling of dislike for a person or group of persons, usually based on stereotype.  Virtually everyone feels some sort of prejudice, whether it's for an ethnic group, or for a religious group, or for a type of person like blondes or fat people or tall people.  The important thing is they just don't like them -- in short, prejudice is a feeling, a belief.  You can be prejudiced, but still be a fair person if you're careful not to act on your irrational dislike.

> Discrimination takes place the moment a person acts on prejudice.  This describes those moments when one individual decides not to give another individual a job because of, say, their race or their religious orientation.  Or even because of their looks (there's a lot of hiring discrimination against "unattractive" women, for example).  You can discriminate, individually, against any person or group, if you're in a position of power over the person you want to discriminate against.  White people can discriminate against black people, and black people can discriminate against white people if, for example, one is the interviewer and the other is the person being interviewed.

> Racism, however, describes patterns of discrimination that are institutionalized as "normal" throughout an entire culture. It's based on an ideological belief that one "race" is somehow better than another "race".  It's not one person discriminating at this point, but a whole population operating in a social structure that actually makes it difficult for a person not to discriminate.  

Seems like "Racism" is the wrong word here. From this definition I'm not certain how you could possibly ban it, regardless of how much all of us wish it were gone it's a result, not something you can do. It's a cultural outcome from condoning discrimination. Without telepathy you can't ban prejudice. What we're talking about here is discrimination. 

By these definitions I can't see how the word racism could possibly fit into a Code of Conduct. Save for maybe a justification of a rule "We will remove you from our community if you are found to be discriminating based on race in order to keep the negative effects of racism out of our community." or "Break the cycle of racism". 

So I see what the idea is here, there cannot be "reverse" racism, since "racism" (by the definition above) only works one way in a culture. I get that, and in that context I agree. 

As the article says, racism != discrimination, so it's not that "cis" people are exempt from discrimination. You just can't be "cisist". Which again, I agree. 

If a "non-white" neighbour puts up a sign that says "White trespassers will be shot, everyone else gets candy". It is not proof that I am in a "Racist against white people" community. It is, however, is fair to say he's discriminating against white people. (A cringey and contrived example, I'm sorry)

Which I guess was my original concern, on Github is it permissible to discriminate against a overrepresented gender, race, cis, ... based on their gender, race ... ? 

I would hope that is not allowed, and based on the information from this article I'm guessing that it is not allowed. 

Which then begs the question, why does this even mention "reversisms" at all. Perhaps you could provide an example of what activity or behaviour could induce that clause?

As an aside, which I'm not certain I should include, but feel it's important. The first link you referenced is hosted on a extremist left-wing american-specific blog. While in this case it's content was relevant the place it's hosted is far from fair and unbiased, but I generally take that as a sign of a narrow or biased view, which is not a good thing to have when setting guidelines for a worldwide, diverse community like GitHub (and other large projects as I understand).

As a centrist canadian my environment is very different from yours, congrats on legalizing gay marriage :smiley: it's been the norm here for more than half my life. 

As you can see from the shitstorm of comments and other issues surrounding this, while it may sound fair and necessary, if it's too vague it can be misinterpreted.

@everyone-else-in-this-thread Before you post, please stop, read it and answer the following "Is this specific and relevant to the github issue I'm commenting on?". If not, either correct it until it is or go back to youtube.

**Comment by atarzwell** [comment]
@bkeepers Also, Where is the work to resolve this happening? I can't seem to find it.

 (Forgive my failure to google, but the signal to noise in the repo is pretty low at the moment.)

**Comment by bkeepers** [comment]
Thanks for your feedback. See https://github.com/todogroup/opencodeofconduct/issues/84.
