### ISSUE TITLE
Make it easy to apply the code of conduct

### ISSUE THREAD

**Issue by bkeepers** [todogroup/opencodeofconduct#7]
What if, instead of making this a template that projects have to fork and modify, we make it configurable and linkable?

Basically, I'm imagining something like the [jQuery UI Download Builder](http://jqueryui.com/download/) where maintainers could fill in a few fields, but instead of a customer download, they would get a URL with their values encoded in it, and a copy/pasta-able snippet for `README`/`CONTRIBUTING`:

```
This project adheres to the [Open Code of Conduct](url/with/encoded/values).
By participating in this project, you are expected to uphold this code.`
```

**Comment by caniszczyk** [comment]
+1 I actually love this idea to make it simpler to use, not sure if I would consider this a blocker but more of a "nice to have" (if someone has time to implement it)

**Comment by bkeepers** [comment]
Check out https://github.com/todogroup/opencodeofconduct/pull/10
