### ISSUE TITLE
Code of Conduct Plural

### ISSUE THREAD

**Issue by bbogin** [todogroup/opencodeofconduct#72]
Love the code. One nitpicky thing, though:

I think the plural of "code of conduct" is "codes of conduct," not "code of conducts."

**Comment by atarzwell** [comment]
https://en.wiktionary.org/wiki/code_of_conduct#Noun

Good eye :+1:

**Comment by bkeepers** [comment]
Thanks for your feedback. See https://github.com/todogroup/opencodeofconduct/issues/84.
