### ISSUE TITLE
Privilege doesn't exist.

### ISSUE THREAD

**Issue by MallocNull** [todogroup/opencodeofconduct#73]
There are only those who do and those who complain about how they can't do without putting in effort to be able to do what others can do.

**Comment by atarzwell** [comment]
Correct or not, This is far from constructive.

They seem willing to work with the community which is a necessity for developing a community Code of Conduct. Open an issue to discuss. If you don't want to get involved in the bikeshedding party. Then read others contributions and bust out the thumbs :+1:  or :-1: so we have a articulate communal voice as a community. 

If they are unwilling to work, that will become apparent, and hopefully github will find a less biased team to develop a community Code of Conduct. 

If you crapflood threads, it gives them power to close them without addressing legitimate issues in them. 

I mean this with no disrespect. 

I would love to have gotten an answer to @just3ws 's final comment on #17 but the derailed conversation got it closed :unamused:

**Comment by MallocNull** [comment]
How can you say that this isn't constructive if a large portion of the narrative here relies on the fact that the marxist idea of the oppressor and the oppressed is actually a reality when it's far from the truth and is just liberal propaganda. This is a website on the internet about uploading and sharing code, you don't have to tell anyone you're a queersexual demipan ultraguy megaminority or whatever, you can achieve success on your merits alone, which is how it should be anyways.

**Comment by NuckChorris** [comment]
There will always be people who act like massive assholes online, and a code of conduct serves to prevent that.

Now let's stop acting like edgy channers and start being productive. If you don't like the CoC, either propose a fix or don't use it.

**Comment by flashwave** [comment]
> edgy channers

hurr

**Comment by MallocNull** [comment]
A fix would be to disregard it entirely. Let everyone speak freely as they choose, and those words which are truly important will prevail.

**Comment by atarzwell** [comment]
I'm on your side with intent. I believe the majority here is. It's the method I disagree with. 

This is GitHub, we make great things and are a prime example of the wonder that is the meritocracy. I don't care your color, opinions or who you voted for. I truly don't, if you got good codez, welcome to the team. 

I'm not certain there was enough of an issue to require a CoC, but it's here, and rather that whine or mock it while they decide it's wording, lets speak up to make it the best damned CoC we can. 

The one GitHub chooses will likely be copypasta'd to other repos (or worse, by default). So it's important to make this one count. 

We are the community, either we speak up as one and make a CoC that includes all of us fairly, or we prove the unreasonable bias of this one and have solid grounds to demand they select a better team. 

Or don't, I'm not your boss, but making us who disagree with it's current state look like unreasonable jerks isn't helping.

**Comment by MallocNull** [comment]
Then perhaps a good way to go would be to remove everything in there that has to do with privilege and especially the extremely contradictory clause regarding "reverse 'ism's", since that has hardly anything to with how GitHub functions or the meritocratic idea behind institutions of science and engineering.

**Comment by atarzwell** [comment]
>Then perhaps a good way to go would be to remove everything in there that has to do with privilege and especially the extremely contradictory clause regarding "reverse 'ism's", since that has hardly anything to with how GitHub functions or the meritocratic idea behind institutions of science and engineering.

I agree! There's one that does exactly that! You should support it! :smiley:

#70 

https://github.com/todogroup/opencodeofconduct/pull/70/files#diff-d680e8a854a7cbad6d490c445cba2ebaL37

**Comment by NuckChorris** [comment]
@MallocNull yes, see basically every issue and PR created in the last 24 hours. It's being discussed, they're aware that the wording is sub-optimal.

**Comment by epsalon** [comment]
This entire thread constitutes harassment and abuse.

**Comment by atarzwell** [comment]
> This entire thread constitutes harassment and abuse.

I think Poe's law is in effect here...

If this is a serious concern could you please elaborate?

**Comment by just3ws** [comment]
@atarzwell I'd love to get an answer too but I think the core team has made up their mind and isn't interested in a discussion. On the contrary, there's opinion threads like these that don't seem to actually add anything meaningful and are more a declaration of an individual's opinions. So we have one side stating their opinion and the other stating their opinions but there seems to be little movement towards a center of understanding.

**Comment by bkeepers** [comment]
Thanks for your feedback. See https://github.com/todogroup/opencodeofconduct/issues/84.
