### ISSUE TITLE
isn't religion just an opinion?

### ISSUE THREAD

**Issue by sheepdestroyer** [todogroup/opencodeofconduct#75]
```
+Harassment includes:
+
+- Offensive comments related to gender, gender identity and expression, sexual orientation, disability, mental illness, neuro(a)typicality, physical appearance, body size, race, age, or religion
```
While all other traits are intrinsically constitutive of the person, religion is only an opinion that anyone is free to change at anytime.
I see the inclusion of religion as a potential deny of critical thinking/discussion. So if mere ideas are OK to be protected from offense why stop there and not forbid harassment for political ideas too?

I really believe in respect of the person (and that it must be enforced), but do not think opinions are worthy of such respect. That would in fact be a dangerous idea for liberties.

**Comment by sheepdestroyer** [comment]
the meme version : https://pbs.twimg.com/media/B7Wz261CIAAQLs4.jpg:large

**Comment by bkeepers** [comment]
Hey @sheepdestroyer, thanks for sharing your thoughts. Dialog of ideas and beliefs is certainly welcome, but discrimination and harassment of people for their beliefs is not conducive to the type of open source projects we want to create. You're welcome to open a pull request with suggested changes, but I doubt dropping religion from that list will fly without clarification elsewhere.

**Comment by sheepdestroyer** [comment]
I do not welcome or advocate discrimination and harassment of people for their beliefs.

However as stated in the policy now, it becomes harassment to merely offend religious people. That is extremely wrong. Religious people can chose to be offended by anything. According a "right not to be offended", is going counter to all advance by modern societies. Is is very wrong and very dangerous to put religions (just an other opinion) on the same level as intrinsic properties of what a person is : sex, genre, race, etc...

Historically (and still very much now!) religions have been the primary sources of obscurantism and persecutions. Societies fought back and began separating states and religions, according a right to blasphemy in many cases. The right to blasphemy has been primordial in freeing people from the control of churches. 

Nowadays, we see a weakening of the Age of Enlightenment's philosophical advances : https://en.wikipedia.org/wiki/Age_of_Enlightenment
Religious groups everywhere try to weaken once again civil liberties by asking for this right to be offended and to forbid blasphemy. 

Letting them having their way redefining what is socially acceptable would be a moral and philosophical regression.  Accepting this would not be fighting against discrimination but calling for it.
