### ISSUE TITLE
open code of conduct code of conduct

### ISSUE THREAD

**Issue by sstjohn** [todogroup/opencodeofconduct#81]
Assuming that the Open Code of Conduct development is governed by the Open Code of Conduct, what is the contact information for reporting issues?

Iow, is there a filled-out copy of the template somewhere?

**Comment by sstjohn** [comment]
Oh, I get it-- the answer is 'abuse@todogroup.org. That should probably be visible in README.md.

**Comment by sstjohn** [comment]
see also https://github.com/todogroup/opencodeofconduct/pull/57

**Comment by bkeepers** [comment]
Thanks for your feedback. See https://github.com/todogroup/opencodeofconduct/issues/84.
