### ISSUE TITLE
How about removing the "reverse -isms" bit?

### ISSUE THREAD

**Issue by giulioprisco** [todogroup/opencodeofconduct#82]
I wish to respectfully suggest that to remove the "reverse -isms" bit. I think it does much more harm than good.

"Reverse" racism is just racism, and "reverse" sexism is just sexism. The current text means that attacking some persons for their ethnicity, gender, and sexual orientation is not OK, but attacking some other persons for their ethnicity, gender, and sexual orientation is OK. That directly contradicts previous statements in the Open Code of Conducts itself, as well as the Universal Declaration of Human Rights.

If that's not what you mean, please consider rewording. But I think it would be better to remove those few lines. A good old "no discrimination" policy permits fighting all trolls and acting against all types of harassment. Do you really need to complicate things with "positive discrimination," which many consider as a dangerous oxymoron?

More thoughts here: https://hacked.com/github-promotes-reverse-racism-sexism/

I agree with everything else in the Open Code of Conduct, but this is a serious problem as indicated by several other posts here. I won't participate in online discussion spaces that _explicitly condone_ racism and sexism, and in my opinion that's what the current version of the Open Code of Conduct does.

**Comment by CoWinkKeyDinkInc** [comment]
Almost all pull requests already have these removed.  So it might not be long.

**Comment by CiaranLaval** [comment]
Positive discrimination or affirmative action serve a purpose and are protected by human rights legislation.

The reverse-isms section of the code of conduct is not positive discrimination, it reads as plain discrimination.

**Comment by giulioprisco** [comment]
Thanks for replying. Yes, I see that there are many pull requests to have the "reverse -isms" bit removed. I hope it is removed soon.

**Comment by bkeepers** [comment]
Thanks for your feedback. See https://github.com/todogroup/opencodeofconduct/issues/84.
