### ISSUE TITLE
publications of private communications

### ISSUE THREAD

**Issue by condret** [todogroup/opencodeofconduct#85]
in your definitions of harassment it is written, that "Publication of non-harassing private communication" is seen as harassment. Even though it is written that harassment is not limited to those definitions of harassment, i see a problem here: It implies that there are situations and circumstances that justify publications of private communications, meanwhile it is not said how the person who makes the communication public gets access to this communication.

**Comment by CoWinkKeyDinkInc** [comment]
Take a look at #84, this repository is currently being paused and rewritten.

**Comment by condret** [comment]
i won't read all that stuff in #84, but i can wait until that rewrite is done

**Comment by bkeepers** [comment]
Thanks for your feedback. See #84.
