### ISSUE TITLE
Quality of the Open Code of Conduct seems a bit iffy.

### ISSUE THREAD

**Issue by Ainok** [todogroup/opencodeofconduct#89]
I'm not entirely sure what's going on, or why lots of large companies are still using this. But there seems to be a lot of random nonsense in the latest open code of conduct.

Stuff that's bolded is made up of words that exist in no modern dictionary; italicised words don't seem to make any sort of sense.

>Our open source community prioritizes marginalized people’s safety over *privileged people*’s comfort. We will not act on complaints regarding:

>**‘Reverse’ -isms**, including ‘**reverse racism,**’ **‘reverse sexism,’** and **‘cisphobia’**
>Refusal to explain or debate social justice concepts
>Criticizing racist, sexist, **cissexist**, or otherwise *oppressive behavior* or assumptions

>Deliberate **misgendering**. This includes **deadnaming** or persistently using a pronoun that does not correctly reflect a person's *gender identity*. You must address people by the name they give you when not addressing them by their username or handle

When I say, "don't seem to make any sort of sense", I mean, what on earth is classified as a "privileged person" or "oppressive behaviour"?

**Comment by preoctopus** [comment]
We've been asking repeatedly, check the closed issues, they refuse to clarify or explain it. Now they "paused" it but haven't removed the blog post soliciting it, nor made any mention of the pause in the repo save for the one issue. 

Given the lack of response the best explanation is someone got fed up with trying to talk reasonably, and has started legal action on it's current discriminatory state. If you google Mathew Hopkins + github you should find his blog outlining the action taken so far. 

(I'm not going to link it here as I presume that'll get me banned.)

**Comment by davblayn** [comment]
Here's two key commits I take issue with. f05fd4eea62fc1f7fde00f42b76d4dea97d07642, where they've gleefully added the condescending XKCD comic that people wave around as if it's a shield for criticism, and, of course, b00eff579ded8c76cee0d2cb6b5beed6e84258fb, where a **GitHub employee** decided to add the lovely remark about "reverse-isms" not existing.

I sickened that companies are actually adopting this.

**Comment by bkeepers** [comment]
Thanks for your feedback. See #84.
